// FE_REQUEST
export const URL_DATA_NICK_NAME_FRONT = {
  DATA_NICK_NAME_FRONT: process.env.API_DATA_NICK_NAME_FRONT,
}
// BE_REQUEST
export const URL_DATA_NICK_NAME_BACK = {
  DATA_NICK_NAME_BACK: process.env.API_DATA_NICK_NAME_BACK,
}